# permissions for end users to edit githubissues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubissue-editor-role
rules:
- apiGroups:
  - training.redhat.com
  resources:
  - githubissues
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - training.redhat.com
  resources:
  - githubissues/status
  verbs:
  - get
